--dodanie pola stagedate do tabel stage z komisji faunistycznej i nadanie danym stagedate z czasu ich imporu
ALTER TABLE STAGE.ANNEX
ADD COLUMN STAGEDATE DATE DEFAULT CURRENT_DATE;

ALTER TABLE STAGE.ANNEX RENAME TO ANNEX_OLD;

CREATE TABLE STAGE.ANNEX (
	STAGEDATE DATE DEFAULT CURRENT_DATE,
	LATIN_NAME VARCHAR(32),
	POLISH_NAME VARCHAR(32),
	ENGLISH_NAME VARCHAR(32),
	CATEGORY CHAR(1),
	STATUS VARCHAR(5)
);

INSERT INTO STAGE.ANNEX (STAGEDATE, LATIN_NAME, POLISH_NAME, ENGLISH_NAME, CATEGORY, STATUS)
SELECT '2024-05-23', LATIN_NAME, POLISH_NAME, ENGLISH_NAME, CATEGORY, STATUS
FROM STAGE.ANNEX_OLD;

DROP TABLE STAGE.ANNEX_OLD;


ALTER TABLE STAGE.CATEGORY
ADD COLUMN STAGEDATE DATE DEFAULT CURRENT_DATE;

ALTER TABLE STAGE.CATEGORY RENAME TO CATEGORY_OLD;

CREATE TABLE STAGE.CATEGORY (
	STAGEDATE DATE DEFAULT CURRENT_DATE,
	CATEGORY CHAR(1),
	DESCRIPTION VARCHAR(256)
);

INSERT INTO STAGE.CATEGORY (STAGEDATE, CATEGORY, DESCRIPTION)
SELECT '2024-05-23', CATEGORY, DESCRIPTION
FROM STAGE.CATEGORY_OLD;

DROP TABLE STAGE.CATEGORY_OLD;


ALTER TABLE STAGE.LIST
ADD COLUMN STAGEDATE DATE DEFAULT CURRENT_DATE;

ALTER TABLE STAGE.LIST RENAME TO LIST_OLD;

CREATE TABLE STAGE.LIST (
	STAGEDATE DATE DEFAULT CURRENT_DATE,
	LATIN_NAME VARCHAR(32),
	POLISH_NAME VARCHAR(32),
	ENGLISH_NAME VARCHAR(32),
	CATEGORY CHAR(1),
	STATUS VARCHAR(5)
);

INSERT INTO STAGE.LIST (STAGEDATE, LATIN_NAME, POLISH_NAME, ENGLISH_NAME, CATEGORY, STATUS)
SELECT '2024-05-23', LATIN_NAME, POLISH_NAME, ENGLISH_NAME, CATEGORY, STATUS
FROM STAGE.CATEGORY_OLD;

DROP TABLE STAGE.LIST_OLD;


ALTER TABLE STAGE.STATUS
ADD COLUMN STAGEDATE DATE DEFAULT CURRENT_DATE;

ALTER TABLE STAGE.STATUS RENAME TO STATUS_OLD;

CREATE TABLE STAGE.STATUS (
	STAGEDATE DATE DEFAULT CURRENT_DATE,
	STATUS VARCHAR(3),
	DESCRIPTION VARCHAR(256)
);

INSERT INTO STAGE.STATUS (STAGEDATE, STATUS, DESCRIPTION)
SELECT '2024-05-23', STATUS, DESCRIPTION
FROM STAGE.STATUS_OLD;

DROP TABLE STAGE.STATUS_OLD;