CREATE TABLE DWH.BIRD_SPECIE (
	ID SERIAL PRIMARY KEY,
	POLISH_NAME VARCHAR(32),
	ENGLISH_NAME VARCHAR(32),
	LATIN_NAME VARCHAR(32),
	CATEGORY CHAR(1),
	STATUS VARCHAR(5),
	IS_AVIFAUNA BOOLEAN,
	TIER CHAR(1) DEFAULT '-' CHECK (TIER IN ('S', 'A', 'B', 'C', 'D', 'E', 'F', '-')),
	IS_SEEN BOOLEAN DEFAULT FALSE
);