DELETE FROM DWH.OBSERVATION WHERE BIRD_SPECIE_ID IS NULL OR LOCATION_ID IS NULL;

ALTER TABLE DWH.OBSERVATION 
ALTER COLUMN BIRD_SPECIE_ID SET NOT NULL;

ALTER TABLE DWH.OBSERVATION 
ALTER COLUMN LOCATION_ID SET NOT NULL;

ALTER TABLE DWH.OBSERVATION 
ALTER COLUMN BIRD_COUNT SET NOT NULL;