INSERT INTO DWH.BIRD_SPECIE (
	POLISH_NAME, 
	ENGLISH_NAME, 
	LATIN_NAME, 
	CATEGORY, 
	STATUS, 
	IS_AVIFAUNA) 
SELECT 
	POLISH_NAME AS POLISH_NAME, 
	ENGLISH_NAME AS ENGLISH_NAME, 
	LATIN_NAME AS LATIN_NAME, 
	CATEGORY AS CATEGORY, 
	STATUS AS STATUS, 
	TRUE AS IS_AVIFAUNA
FROM STAGE.LIST
WHERE STAGEDATE = (SELECT MAX(STAGEDATE) FROM STAGE.LIST)
ON CONFLICT (POLISH_NAME)
DO UPDATE SET
	ENGLISH_NAME = EXCLUDED.ENGLISH_NAME, 
	LATIN_NAME = EXCLUDED.LATIN_NAME, 
	CATEGORY = EXCLUDED.CATEGORY, 
	STATUS = EXCLUDED.STATUS, 
	IS_AVIFAUNA = EXCLUDED.IS_AVIFAUNA
;

INSERT INTO DWH.BIRD_SPECIE (
	POLISH_NAME, 
	ENGLISH_NAME, 
	LATIN_NAME, 
	CATEGORY, 
	STATUS, 
	IS_AVIFAUNA) 
SELECT 
	POLISH_NAME AS POLISH_NAME, 
	ENGLISH_NAME AS ENGLISH_NAME, 
	LATIN_NAME AS LATIN_NAME, 
	CATEGORY AS CATEGORY, 
	STATUS AS STATUS, 
	FALSE AS IS_AVIFAUNA
FROM STAGE.ANNEX
WHERE STAGEDATE = (SELECT MAX(STAGEDATE) FROM STAGE.ANNEX)
ON CONFLICT (POLISH_NAME)
DO UPDATE SET
	ENGLISH_NAME = EXCLUDED.ENGLISH_NAME, 
	LATIN_NAME = EXCLUDED.LATIN_NAME, 
	CATEGORY = EXCLUDED.CATEGORY, 
	STATUS = EXCLUDED.STATUS, 
	IS_AVIFAUNA = EXCLUDED.IS_AVIFAUNA
;

UPDATE DWH.BIRD_SPECIE
SET TIER = 'X'
WHERE UPPER(STATUS) LIKE '%Z%' AND IS_AVIFAUNA = TRUE AND STATUS NOT LIKE 'l%';