SELECT * FROM DWH.LOCATION ORDER BY area, name;

UPDATE DWH.LOCATION
SET IS_ACTIVE = FALSE;

INSERT INTO DWH.LOCATION (AREA, NAME, COORDINATES, IS_ACTIVE)
SELECT
    CASE
        WHEN STRPOS(NAME, ' - ') > 0
        THEN SUBSTRING(NAME FROM 1 FOR STRPOS(NAME, ' - ') - 1)
        ELSE 'None'
    END AS AREA,
    CASE
        WHEN STRPOS(NAME, ' - ') > 0
        THEN SUBSTRING(NAME FROM STRPOS(NAME, ' - ')+3)
        ELSE NAME
    END AS NAME,
	COORDINATES AS COORDINATES,
	TRUE AS IS_ACTIVE
FROM STAGE.GOOGLE_MAPS_LOCATION
WHERE 1 =1 
	AND NAME ~ '^[A-Z]'
	AND STAGEDATE = CURRENT_DATE
--if name changes for unchanged coords it will be updated
ON CONFLICT ((COORDINATES::TEXT))
DO UPDATE SET
	NAME = EXCLUDED.NAME,
	AREA = EXCLUDED.AREA,
	IS_ACTIVE = EXCLUDED.IS_ACTIVE
;