INSERT INTO DWH.LOCATION (AREA, NAME, COORDINATES)
SELECT
    CASE
        WHEN STRPOS(NAME, ' - ') > 0
        THEN SUBSTRING(NAME FROM 1 FOR STRPOS(NAME, ' - ') - 1)
        ELSE NULL
    END AS AREA,
    CASE
        WHEN STRPOS(NAME, ' - ') > 0
        THEN SUBSTRING(NAME FROM STRPOS(NAME, ' - ')+3)
        ELSE NAME
    END AS NAME,
	COORDINATES AS COORDINATES
FROM STAGE.GOOGLE_MAPS_LOCATION
WHERE 1 =1 
	AND NAME ~ '^[A-Z]'
	AND STAGEDATE = CURRENT_DATE
--if name changes for unchanged coords it will be updated
ON CONFLICT ((COORDINATES::TEXT))
DO UPDATE SET
	NAME = EXCLUDED.NAME
;